import type { RetroResponse } from "@/lib/retro-schemas";

type Props = {
  retro: RetroResponse;
  sampleLabel: string;
  /** "live" — real Anthropic call. "fallback" — canned response. */
  source: "live" | "fallback";
};

/**
 * Stagger-animated retro output. Four sections (went well / slowed / learnings /
 * additions) plus a closing accent-dot caption. The same component renders for
 * both live API responses and canned fallback responses (ADR-0025) — only the
 * caption text + dot color differ.
 */
export function RetroOutput({ retro, sampleLabel, source }: Props) {
  const isFallback = source === "fallback";
  const captionText = isFallback
    ? "API call paused, showing a sample retrospective"
    : "Generated by a real Anthropic API call · prompt + transcript only · no persistence";

  return (
    <section className="lab-retro lab-stag" aria-label="Retrospective output">
      <header className="lab-retro-header">
        <div>
          <span className="kicker">Session retro / draft</span>
          <h3>
            Reading: <em>{sampleLabel}</em>
          </h3>
        </div>
        <span className="lab-retro-meta">{formatTimestamp()}</span>
      </header>

      <Section idx={0} kicker="01" title="What went well">
        <ul className="lab-retro-bullets">
          {retro.wentWell.map((b, i) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: bullets render in fixed model order
            <li key={i}>{b}</li>
          ))}
        </ul>
      </Section>

      <Section idx={1} kicker="02" title="What slowed things down">
        <ul className="lab-retro-bullets">
          {retro.slowed.map((b, i) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: bullets render in fixed model order
            <li key={i}>{b}</li>
          ))}
        </ul>
      </Section>

      <Section idx={2} kicker="03" title="Learnings catalogue">
        <div className="lab-retro-learnings">
          {retro.learnings.map((l, i) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: learnings render in fixed model order
            <article key={i} className="lab-retro-learning">
              <span className="tag">L-{String(i + 1).padStart(2, "0")}</span>
              <h5>{l.title}</h5>
              <p>{l.body}</p>
            </article>
          ))}
        </div>
      </Section>

      {retro.additions.length > 0 ? (
        <Section idx={3} kicker="04" title="Suggested additions">
          <div className="lab-retro-additions">
            {retro.additions.map((a, i) => (
              // biome-ignore lint/suspicious/noArrayIndexKey: additions render in fixed model order
              <div key={i} className="lab-retro-addition">
                <code>{a.title}</code>
                <span>{a.body}</span>
              </div>
            ))}
          </div>
        </Section>
      ) : null}

      <p className="lab-retro-caption" data-fallback={isFallback || undefined}>
        <span className="lab-retro-caption-dot" aria-hidden="true" />
        {captionText}
      </p>
    </section>
  );
}

type SectionProps = {
  idx: number;
  kicker: string;
  title: string;
  children: React.ReactNode;
};

function Section({ idx, kicker, title, children }: SectionProps) {
  return (
    <div className="lab-retro-section lab-stag" style={{ animationDelay: `${idx * 90}ms` }}>
      <div className="lab-retro-section-head">
        <span className="kicker">{kicker}</span>
        <h4>{title}</h4>
      </div>
      {children}
    </div>
  );
}

function formatTimestamp(): string {
  // Avoid Intl locale-dependent output to keep SSR/CSR matching deterministic
  // for the rare case this is rendered server-side.
  const d = new Date();
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  const month = months[d.getMonth()] ?? "Jan";
  const day = d.getDate();
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${month} ${day} · ${hh}:${mm}`;
}
